media:
  input: d27179db977796e7e2e67f6dabc9b081
  output: /d27179db977796e7e2e67f6dabc9b081

content:
  - name: projects
    label: Projects
    type: collection
    path: projects
    filename: "{slug}.md"
    fields:
      - name: title
        label: Title
        type: string
      - name: year
        label: Year
        type: string
      - name: body
        label: Body
        type: rich-text