media:
  input: d27179db977796e7e2e67f6dabc9b081
  output: /d27179db977796e7e2e67f6dabc9b081

content:
  - name: pages
    label: Pages (HTML)
    type: collection
    path: .
    filter: "*.html"
    fields:
      - name: body
        label: HTML
        type: code
        options:
          language: html

collections:
- name: typekit
    label: Typekit files
    type: collection
    path: use.typekit.net
    fields:
      - name: body
        label: File
        type: code