media:
  input: cdn.myportfolio.com/d27179db977796e7e2e67f6dabc9b081
  output: /cdn.myportfolio.com/d27179db977796e7e2e67f6dabc9b081

content:
  - label: Home
    name: index
    type: file
    path: index.html
    fields:
      - { name: body, label: HTML, type: code, options: { format: html } }

  - label: Work
    name: work
    type: file
    path: work.html
    fields:
      - { name: body, label: HTML, type: code, options: { format: html } }

  - label: Contact
    name: contact
    type: file
    path: contact.html
    fields:
      - { name: body, label: HTML, type: code, options: { format: html } }
